name: Run Zee Script and Release New Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for detecting changes

      - name: Run Zee Script
        run: |
          chmod +x zee.sh
          ./zee.sh
          env >> $GITHUB_ENV
          
      - name: Commit and Push CURRENT_VERSION Changes
        if: env.HAS_RELEASE_FILE == '1'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.VERSION_FILE }} ${{ env.JSON_FILE}}
          git commit -m "Auto-update"
          git push origin main

      - name: Create GitHub Release
        if: env.HAS_RELEASE_FILE == '1'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILE }}
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_FILE }}
          body: "Automatically generated release from GitHub Actions."
          draft: false
          prerelease: false