name: Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "TAG_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "VERSION_FILE=CURRENT_VERSION" >> $GITHUB_ENV
          echo "REPO=$(basename '${{ github.repository }}')" >> $GITHUB_ENV

      - name: Find JSON Files
        run: |
          JSON_FILES=()
          for type in monet black; do
            JSON_FILE="./${{ env.REPO }}/${type}-og.json"
            [ -f "$JSON_FILE" ] && JSON_FILES+=("$JSON_FILE")
          done
          echo "JSON_FILES=${JSON_FILES[@]}" >> $GITHUB_ENV

      - name: Run Zee Script
        run: |
          chmod +x zee.sh
          ./zee.sh

      - name: Verify Release Files
        run: |
          RELEASE_FILES=()
          for type in monet black; do
            RELEASE_FILE="./${{ env.REPO }}-${type}-og.zip"
            [ -f "$RELEASE_FILE" ] && RELEASE_FILES+=("$RELEASE_FILE")
          done
          echo "RELEASE_FILES=${RELEASE_FILES[@]}" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.RELEASE_FILES != ''
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.VERSION_FILE }} ${{ env.JSON_FILES }}
          git commit -m "Auto-update"
          git push origin main

      - name: Create GitHub Release
        if: env.RELEASE_FILES != ''
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILES }}
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "Automatically generated release from GitHub Actions."
          draft: false
          prerelease: false