name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [monet, black]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          AUTHOR="${{ github.repository_owner }}"
          REPO=$(basename "${{ github.repository }}")
          echo "AUTHOR=${AUTHOR}" >> $GITHUB_ENV
          echo "REPO=${REPO}" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "JSON_FILE=./${REPO}/${{ matrix.type }}-og.json" >> $GITHUB_ENV
          echo "RELEASE_FILE=./${REPO}-${{ matrix.type }}-og.zip" >> $GITHUB_ENV

      - name: Run Zee Script
        run: |
          chmod +x zee.sh
          ./zee.sh "${{ matrix.type }}"

      - name: Verify Release File
        run: |
          if [ -f "${{ env.RELEASE_FILE }}" ]; then
            echo "TO_UPDATE=true" >> $GITHUB_ENV
          else
            echo "TO_UPDATE=false" >> $GITHUB_ENV
          fi
          
      - name: Updated
        if: ${{ env.TO_UPDATE == 'false' }}
        run: |
          echo "You're using the latest version."
          exit 0
          
      - name: Create GitHub Release
        if: ${{ env.TO_UPDATE == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILE }}
          tag_name: ${{ env.TAG_NAME }}
          name: "${{ env.REPO }} - ${{ env.TAG_NAME }}"
          body: "${{ env.AUTHOR }} YouTube Lite Magisk Module."
          draft: false
          prerelease: false

      - name: Commit and Push Changes
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase
          git add "${{ env.JSON_FILE }}"
          git commit -m "Auto-update YouTube (${{ matrix.type }}-og)"
          git push origin main
          