name: Run Zee Script and Release New Files

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Zee Script
        run: |
          source ./utils.sh
          
          CURRENT_VERSION=$(cat "$VERSION_FILE")

          check_dependencies curl unzip jq
          update
          
          env >> $GITHUB_ENV
          
      - name: Verify File for Release
        run: |
          if [ -f "${{ env.RELEASE_FILE }}" ]; then
            echo "HAS_RELEASE_FILE=true" >> $GITHUB_ENV
          else
            echo "HAS_RELEASE_FILE=false" >> $GITHUB_ENV
          fi
      
      - name: Commit and Push Changes
        if: env.HAS_RELEASE_FILE == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.VERSION_FILE }} ${{ env.JSON_FILE}}
          git commit -m "Auto-update"
          git push origin main
          
      - name: Create GitHub Release
        if: env.HAS_RELEASE_FILE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILE }}
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_FILE }}
          body: "Automatically generated release from GitHub Actions."
          draft: false
          prerelease: false
          