name: Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [monet, black]  # Creates two jobs: one for monet, one for black

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          REPO=$(basename "${{ github.repository }}")
          echo "TAG_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "VERSION_FILE=CURRENT_VERSION" >> $GITHUB_ENV
          echo "JSON_FILE=${REPO}/${{ matrix.type }}-og.json" >> $GITHUB_ENV
          echo "RELEASE_FILE=${REPO}-${{ matrix.type }}-og.zip" >> $GITHUB_ENV

      - name: Run Zee Script
        run: |
          chmod +x zee.sh
          ./zee.sh "${{ matrix.type }}"

      - name: Verify Release File
        run: |
          if [ ! -f "${{ env.RELEASE_FILE }}" ]; then
            echo "Error: Release file not found!"
            exit 1
          fi

      - name: Commit and Push Changes
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "${{ env.VERSION_FILE }}" "${{ env.JSON_FILE }}"
          git commit -m "Auto-update YouTube (${{ matrix.type }}-og)"
          git push origin main

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILE }}
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }} - YouTube (${{ matrix.type }}-og)"
          body: "Automatically generated release for YouTube (${{ matrix.type }}-og)."
          draft: false
          prerelease: false