name: Run Zee Script and Release New Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for detecting changes

      - name: Save Initial File List and Hash
        run: |
          ls -1 > initial_files.txt
          if [ -f CURRENT_VERSION ]; then
            sha256sum CURRENT_VERSION > current_version_before.txt
          fi

      - name: Run Zee Script
        run: |
          chmod +x zee.sh
          ./zee.sh

      - name: Detect New Files
        run: |
          ls -1 > after_files.txt
          NEW_FILES=$(comm -13 <(sort initial_files.txt) <(sort after_files.txt) | tr '\n' ' ')
          echo "NEW_FILES=${NEW_FILES}" >> $GITHUB_ENV

      - name: Check for Changes in CURRENT_VERSION
        run: |
          if [ -f CURRENT_VERSION ]; then
            sha256sum CURRENT_VERSION > current_version_after.txt
            if ! diff -q current_version_before.txt current_version_after.txt > /dev/null; then
              echo "CURRENT_VERSION_MODIFIED=true" >> $GITHUB_ENV
            fi
          fi

      - name: Commit and Push CURRENT_VERSION Changes
        if: env.CURRENT_VERSION_MODIFIED == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add CURRENT_VERSION
          git commit -m "Auto-update CURRENT_VERSION"
          git push origin main

      - name: Generate Tag Name
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Verify Files for Release
        run: |
          FILES="CURRENT_VERSION ZEE-YT-monet-og.zip utils.sh zee-yt zee.sh"
          RELEASE_FILES=""
          for FILE in $FILES; do
            if [ -e "$FILE" ]; then
              RELEASE_FILES="$RELEASE_FILES $FILE"
            else
              echo "Skipping missing file: $FILE"
            fi
          done
          echo "RELEASE_FILES=${RELEASE_FILES}" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: env.NEW_FILES != ''
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILES }}
          tag_name: ${{ env.TAG_NAME }}
          name: "New Auto Release"
          body: "Automatically generated release from GitHub Actions."
          draft: false
          prerelease: false