name: Run Zee Script and Release New Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-zee-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for detecting changes

      - name: Run Zee Script
        run: |
          export AUTHOR=${{ github.repository_owner }}
          export FULL_REPO=${{ github.repository }}
          export REPO=$(basename ${{ github.repository }})
          export REPO_TYPE="monet-og"
          export RELEASE_FILE="${REPO}-${REPO_TYPE}.zip"
          export TAG_NAME=$(date +'%Y%m%d')
          
          VERSION_FILE="CURRENT_VERSION"
          JSON_FILE="$REPO/${REPO_TYPE}.json"
          
          echo "VERSION_FILE=${VERSION_FILE}" >> $GITHUB_ENV
          echo "JSON_FILE=${JSON_FILE}" >> $GITHUB_ENV
          echo "RELEASE_FILE=${RELEASE_FILE}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          
          chmod +x zee.sh
          ./zee.sh
          
      - name: Detect Release File
        run: |
          if [ -f "$RELEASE_FILE" ]; then
            echo "HAS_RELEASE_FILE=1" >> $GITHUB_ENV
          else
            echo "HAS_RELEASE_FILE=0" >> $GITHUB_ENV
          fi
          
      - name: Commit and Push CURRENT_VERSION Changes
        if: env.HAS_RELEASE_FILE == '1'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.VERSION_FILE }} ${{ env.JSON_FILE}}
          git commit -m "Auto-update"
          git push origin main

      - name: Create GitHub Release
        if: env.HAS_RELEASE_FILE == '1'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_FILE }}
          tag_name: ${{ env.TAG_NAME }}
          name: "ZEE-YT-monet-og.zip"
          body: "Automatically generated release from GitHub Actions."
          draft: false
          prerelease: false